---
apiVersion: v1
kind: Pod
metadata:
  name: pod-sample
spec:
  containers:
  - name: apache
    image: httpd
    env:
    - name: TEST_SECRET_USERNAME_ENV_VAR
      valueFrom:
        secretKeyRef:
          name: secret-002
          key: username
... 
